---

- name: ensure ~/.profile.d exists
  file: path=~/.profile.d state=directory mode=0755
  tags: misc

- name: misc | Install misc linux tools (mc, screen etc)
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
  with_items: misc_packages
  tags: misc
