---
- name: add ppa key
  become: yes
  apt_key:
    url: 'https://dl.google.com/linux/linux_signing_key.pub'
    state: present

- name: add ppa
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
    filename: 'google-chrome'
    state: present
    update_cache: true


- name: install google-chrome
  become: yes
  apt:
    name: google-chrome-stable

# vim: autoindent tabstop=2 shiftwidth=2 expandtab softtabstop=2
