---

- name: install apt key
  become: true
  apt_key:
    url: "https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key"
  tags: 'cfcli'

- name: setup custom apt repo
  become: true
  apt_repository:
    repo: 'deb https://packages.cloudfoundry.org/debian stable main'
    state: present
  tags: 'cfcli'

- name: update apt cache
  become: true
  apt: update_cache=yes
  tags: 'cfcli'

- name: install cf cli
  become: true
  apt:
    pkg: "cf-cli"
    state: present
  tags: 'cfcli'
