---

- name: enable Ubuntu Extras
  become: yes
  apt_repository:
    repo: 'deb http://mirror.internode.on.net/pub/ubuntu/ubuntu xenial restricted'
    state: present
    update_cache: true
  tags: lubuntu

- name: Install the Lubuntu Meta Package
  become: yes
  apt:
    name: "{{item}}"
    install_recommends: true
  with_items:
    - lubuntu-desktop
    - lubuntu-restricted-addons
    - lubuntu-restricted-extras
  tags: lubuntu

- name: install a sane pulseaudio tray tool
  become: yes
  apt:
    name: "pavucontrol"
    install_recommends: true
  tags: lubuntu

- name: turn boot splash on
  become: yes
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"'
  tags: lubuntu

- name: symlink various config files in from .dotfiles/.config to .config
  file:
    src: "{{dotfiles_dir}}/.config/{{item}}"
    dest: "{{lookup('env','HOME')}}/.config/{{item}}"
    state: link
    force: yes
  with_items: "{{lubuntu_config_files}}"
  when: lubuntu_config_files is defined
  tags: lubuntu
