---

- name: install direnv from package
  sudo: yes
  apt: pkg=direnv state=present
  tags: direnv

- stat: path="{{direnv.rc.src}}"
  register: direnvrcsrc
  tags: direnv

- name: symlink config file into home
  sudo: no
  file:
    src={{ direnv.rc.src }}
    dest={{ direnv.rc.dest }}
    state=link
    force=yes
  when: direnvrcsrc.stat.exists
  tags: direnv
