---

- name: download x86_64 Ubuntu .deb
  get_url:
    url={{ zoom.deb.url }}
    sha256sum={{ zoom.deb.sha256 }}
    dest={{ zoom.deb.dest }}
  tags: zoom

- name: install x86_64 Ubuntu .deb
  apt: deb={{ zoom.deb.dest }}
  become: yes
  tags: zoom

- name: set zoom up to autostart at boot
  copy:
    src: /usr/share/applications/Zoom.desktop
    dest: "/home/{{user}}/.config/autostart/Zoom.desktop"
    mode: 0644
  tags: zoom
