---
- name: conky | install conky
  become: yes
  apt: pkg=conky-std state=installed
  tags: conky

- name: conky | setup ~/.conky
  become: no
  file:
    src={{ conky.dir.src }}
    dest={{ conky.dir.dest }}
    state=link
    force=yes
  tags: conky

- name: conky | setup ~/.conkyrc
  become: no
  file:
    src={{ conky.rc.src }}
    dest={{ conky.rc.dest }}
    state=link
    force=yes
  tags: conky
