---

- name: add the git-core ppa
  become: true
  apt_repository:
    repo: ppa:git-core/ppa
    update_cache: true
    state: present
  when: git.ppa
  tags: git

- name: install git
  become: yes
  apt:
    pkg: git
    state: present
  tags: git

- name: setup ~/.gitconfig
  become: no
  file:
    src=~/.dotfiles/.gitconfig
    dest=~/.gitconfig
    state=link
    force=yes
  tags: git
