---

- name: Download latest golang binary tarball for X86_64 linux
  become: no
  get_url:
    url: "{{golang.url}}"
    dest: "{{golang.tmp_dest}}"
    checksum: "{{golang.checksum}}"
  tags: golang

- name: install golang globally
  become: true
  unarchive:
    src: "{{golang.tmp_dest}}"
    dest: "{{golang.install_dest}}"
  tags: golang

- name: Install ~/.profile.d/golang.sh
  template:
    src: "golang.sh.j2"
    dest: "{{lookup('env','HOME')}}/.profile.d/golang.sh"
    mode: "0644"
    owner: "{{user}}"
    group: "{{user}}"
  tags: golang
