---

- name: install KeePass2
  apt:
    pkg: "{{item}}"
    state: present
  become: true
  tags: keepass2
  with_items:
    - keepass2
    - xdotool

- name: setup ~/.config/KeePass
  become: no
  file:
    src: "{{keepass.src}}"
    dest: "{{keepass.dest}}"
    state: link
    force: true
  tags: keepass2
