---

- name: Download and install the latest bosh-cli
  become: no
  get_url:
    url: "{{boshcli.url}}"
    dest: "{{boshcli.dest}}"
    mode: "0700"
    checksum: "{{boshcli.checksum}}"
  tags: bosh
